project:
  type: website
  output-dir: docs

website:
  title: "Sofia Sarak" # also acts as another home button!
  # favicon: images/favicon.png
  navbar:
    # logo: images/logo.png
    # logo-alt: "description of my logo"
    # title: false ; use if logo and name is repetitive
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - posts.qmd
      - href: resources.qmd
      - icon: github
        href: https://github.com/sofiasarak
      #   text: Resources # makes it "Resources" in taskbar even if page title is different 
  page-footer: 
    left: Copyright 2025, Sofia Sarak
    right:
      - icon: github
        href: https://github.com/sofiasarak/sofiasarak.github.io 

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full # makes it so the text uses the whole screen
    mainfont: Manrope



